### ISSUE TITLE
Communication with Gatekeepers

### ISSUE THREAD

**Issue by SamOBrienOlinger** [SamOBrienOlinger/know-yellowknife#5]

**Comment by SamOBrienOlinger** [comment]
### Task: Engage Main Gatekeeper

#### Description
This issue focuses on identifying and contacting the main gatekeeper for the project, followed by sending the relevant documents for their review.

#### Checklist
- [x] Identify and contact main gatekeeper
- [x] Send relevant documents for review by gatekeeper
- [ ] Receive feedback from gatekeeper
- [ ] Share feedback with team


#### Deadline
[ ] ASAP after Christmas holidays in Yellowknife.
